wc -l nuevarsNT_total.txt
wc -l numpivtxvarsNT_total.txt
wc -l thetavarsNT_total.txt
wc -l alphavarsNT_total.txt
wc -l runvars_total.txt
wc -l energiesvarsNT_total.txt
wc -l energiesALLvarsNT_total.txt
wc -l visenergiesALLvarsNT_total.txt
wc -l recovars_total.txt
wc -l pronglengthvars_total.txt
wc -l pronghitshvars_total.txt
wc -l coorstartvars_total.txt
wc -l dirprongtvars_total.txt
wc -l calenergiesvars_total.txt
wc -l pdgntvars_total.txt
wc -l pdgpngvars_total.txt
wc -l cvnvars_total.txt
wc -l trkNTvars_total.txt
wc -l trkvars_total.txt