cat nuevarsNT.*.txt > nuevarsNT_total.txt
cat numpivtxvarsNT*.txt > numpivtxvarsNT_total.txt
cat thetavarsNT*.txt > thetavarsNT_total.txt
cat alphavarsNT*.txt > alphavarsNT_total.txt
cat runvars*.txt > runvars_total.txt
cat energiesvarsNT*.txt > energiesvarsNT_total.txt
cat energiesALLvarsNT*.txt > energiesALLvarsNT_total.txt
cat visenergiesALLvarsNT*.txt > visenergiesALLvarsNT_total.txt 
cat energies1varsNT*.txt > energies1varsNT_total.txt
cat energies2varsNT*.txt > energies2varsNT_total.txt
cat energies3varsNT*.txt > energies3varsNT_total.txt
cat energies4varsNT*.txt > energies4varsNT_total.txt
cat energies5varsNT*.txt > energies5varsNT_total.txt
cat energies6varsNT*.txt > energies6varsNT_total.txt
cat recovars*.txt > recovars_total.txt
cat pronglengthvars*.txt > pronglengthvars_total.txt
cat pronghitshvars*.txt > pronghitshvars_total.txt
cat coorstartvars*.txt > coorstartvars_total.txt
cat dirprongtvars*.txt > dirprongtvars_total.txt
cat calenergiesvars*.txt >calenergiesvars_total.txt
cat pdgntvars*.txt > pdgntvars_total.txt
cat pdgpngvars*.txt > pdgpngvars_total.txt
cat cvnvars*.txt > cvnvars_total.txt
cat trkNTvars*.txt > trkNTvars_total.txt
cat trkvars*.txt > trkvars_total.txt
